name: daravel
description: A sample command-line application.
publish_to: none
version: 1.0.0
repository: https://github.com/fugindo/daravel

environment:
  sdk: ^3.0.6

dependencies:
  path: ^1.8.3
  shelf: ^1.4.1
  postgres: ^2.6.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
